travis:
  secure:
    BINSTAR_TOKEN: ySkvB/iLbdigb94NTn9GZHryXCtX7us896tcfCt2EmdzZ8iBcHtuSau58xUsVfRrSSLy0vZjSSLtGkAGL/FuoAuA1TvVUj1g4PW/gqZ7Xfz63dq7eYIz5Ty0h6TloZLNv2/RUsQ4ICQx1PKI/oeg50D1jEsJxDZrFB3n8hRHI7SJMQobnUItiCPUwvCMVzpEnCz5rn+4BE7ype+fMFM/1ws2uyibvRoM9ty0Hr+D+sFxFtMBJn6HlWNJw2i6zYx1Ib8kOXGQcVUB9N9SFJBkRaoQkqepmTvZnS3Lxs+sv/AntsA987mY7RAQKWv2NWtcHCpPzwH+3gSRT7Y6y2Jqb91NpaTy6T3WZExWkhjOR9WYIpTZ+daO87S4ThZsvBazsIALP3PzOYYE4a1KDF43HemKuZ9D0IPygOxXTBxnXM8DSDcUA/u0HwAK6H3KzNF9BHRhfZM6FuI+JlPSKFl9t5meNdc2j3g5WlJXHf+U63+7wjRsnV2+vA7H3INEl6feV4+96NkS69RW36tahdDNOoOQ4aJVC45gl9SrQb38M1y2Sub2g/VsKcmknISofbJUWHTd2cenc2zGR0XntjVeeo38f1YHNwn/RSZZ1f7w2+0+0vMN4IzF49CXixZ/6wtKx6SrjwqOcABss0E2yGbY6v3quTkOl7XGW2jISIwPmlw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
