travis:
  secure:
    BINSTAR_TOKEN: rbIRvMrzHj9Ckbgubup4Rx553UYrORo+D2CZxEfhIJuLPTZyLA5lgJyOYV7tKngBLZ9gLeSKfyLCp6Kx8npWvd4Q60W6QNEWcz3nltDTexp7fxwNvLCKMbWkNV3rt1YkD6EQXmGIqlOC6I15Xvt3DcNrrMZ15uRQp/avh8JdarRlh+th4mms4EOm6FWPL7gZJHq8mRpw7NnT33/zpiZwMudOrOMd6m5uaT3KDAWv/CgDlwOvAZLUK9yJRPZuWfVIWs5EVHy/GZ0pba1VnPavZPJnZy/6dahfmaXeqclc71kN9+6tA7E1dVsUqC0KdHo0f0aLj2Ezw2UkHoUNA571omjlDx6p6YAPBvNIscEfOnZH0BEH8K2p6VUZ6mWySyK/FXKHcSNlSQs7zdYLwBZ4fB/AqGjk+N5oqIjPKUmfbPaxenS6qTDPkiIPk85eMBryjzkotomQvjIFTAgdlAkAYvFybOWEkjX0X6TMuvgVlMxlQnALLF8TR4XdVqF9u65onQ1NcvQ44M6/qzSI0QON5YsTlownSQaK/5O0An7/6RePzgmR9yGzrV11pmbubcPAzLQPUtN706eHhvTNTD3+O6p43yIbelqerWP2ueL/clPdwPPjRyy2+6f1GsITcx58nkBmuSxfpcQc8ivzFppE/L5cHUmVS076bxP9fUSYdng=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
